name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
     contents: write
   steps:
     - name: Checkout Commit
       uses: actions/checkout@v2

     - name: Install Rust
       uses: hecrj/setup-rust-action@v1
       with:
         rust-version: 'stable' 
         targets: 'wasm32-unknown-unknown'
         
     - name: Build Regular Shared Library
       run: cargo build --target wasm32-unknown-unknown --release 

     - name: Release
       uses: softprops/action-gh-release@v1
       with:
         generate_release_notes: true
         draft: false
         prerelease: false
         tag_name: release-${{ github.sha }}
         release_name: Release ${{ github.sha }}
         files: |
           ./target/wasm32-unknown-unknown/release/sea_of_stars.wasm

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
          targets: wasm32-unknown-unknown

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
